routerAdd(
  'POST',
  '/backend/v1/payments/confirm',
  (e) => {
    const body = e.requestInfo().body || {}
    const recordId = body.record_id
    if (!recordId) return e.badRequestError('Missing record_id')

    const authId = e.auth && e.auth.id
    if (!authId) return e.unauthorizedError('Auth required')

    let record
    try {
      record = $app.findRecordById('financial_records', recordId)
    } catch (err) {
      return e.notFoundError('Financial record not found')
    }

    if (record.getString('status') !== 'aguardando_confirmacao') {
      return e.badRequestError(
        'Record is not awaiting confirmation. Current status: ' + record.getString('status'),
      )
    }

    // Ownership verification: ensure the user is the record's professional
    // or an admin of the same clinic
    const recordProfessional = record.getString('professional')
    const recordClinic = record.getString('clinic')
    const authUser = e.auth
    const userRole = authUser ? authUser.getString('role') : ''

    var isOwner = recordProfessional === authId
    var isAdminOfClinic =
      (userRole === 'admin_clinica' || userRole === 'gestor_saas') &&
      (authUser ? authUser.getString('contexto_ativo') : '') === recordClinic

    if (!isOwner && !isAdminOfClinic) {
      return e.forbiddenError(
        'You do not have permission to confirm this payment. Only the record owner or a clinic admin can perform this action.',
      )
    }

    const autoGenerated = record.getBool('auto_generated')

    record.set('status', 'pago')
    const now = new Date()
    const dateStr =
      now.getFullYear() +
      '-' +
      String(now.getMonth() + 1).padStart(2, '0') +
      '-' +
      String(now.getDate()).padStart(2, '0')
    record.set('payment_date', dateStr)
    record.set('auto_generated', autoGenerated)

    $app.save(record)

    let notificationSent = true
    try {
      const patientId = record.getString('patient')
      const total = record.get('total') || 0
      const valorStr = total.toFixed(2)

      let patientUserId = ''
      try {
        const patient = $app.findRecordById('patients', patientId)
        patientUserId = patient.getString('profile')
      } catch (err) {}

      if (patientUserId) {
        const notif = new Record($app.findCollectionByNameOrId('notifications'))
        notif.set('profile', patientUserId)
        notif.set('patient', patientId)
        notif.set('title', 'Pagamento Confirmado')
        notif.set('body', 'Seu pagamento de R$ ' + valorStr + ' foi confirmado.')
        notif.set('type', 'pagamento_confirmado')
        notif.set('channel', 'in_app')
        notif.set('status', 'Enviada')
        notif.set('reference_table', 'financial_records')
        notif.set('reference_id', recordId)
        $app.save(notif)
      } else {
        notificationSent = false
      }
    } catch (err) {
      notificationSent = false
      $app
        .logger()
        .error(
          'Failed to send payment confirmation notification',
          'error',
          err.message,
          'recordId',
          recordId,
        )
    }

    return e.json(200, { success: true, notification_sent: notificationSent })
  },
  $apis.requireAuth(),
)
